--[[ WEAPONS — every Tool in ServerStorage ▸ Weapons that players may carry,
     and how it is unlocked. GENERATED by scripts/gen_content.py from its
     WEAPONS table (edit there, or edit here and stop running the script).
       id        the Tool's name        name     shown in menus
       family    "OneHanded" | "TwoHanded" | "Polearm" | "Ranged"   (kill counts and crates group by it)
       ranged    a bow or a crossbow: the Archer's primary, nobody else's (Catalog.weaponFits)
       secondary true = may be carried as the secondary (the Tool's Config SECONDARY must also be true)
       unlock    {free = true} | {level = 5} | {kills = 40, family = "OneHanded"}
       marks     price to buy it outright instead of unlocking (0 = cannot be bought)
       weights   optional list of weights that may carry it; nil = any
     The Tool's body and its menu display copy are built from Build ▸ Weapons
     when no hand-made model exists. ]]
return {
	{id = "Shortsword", name = "Shortsword", family = "OneHanded", secondary = true, unlock = {free = true}},
	{id = "Pitchfork", name = "Pitchfork", family = "Polearm", secondary = false, unlock = {level = 2}, marks = 300},
	{id = "Greatsword", name = "Greatsword", family = "TwoHanded", secondary = false, unlock = {free = true}},
	{id = "Hammer", name = "War Hammer", family = "OneHanded", secondary = true, unlock = {free = true}},
	{id = "ArmingSword", name = "Arming Sword", family = "OneHanded", secondary = true, unlock = {free = true}},
	{id = "Dagger", name = "Rondel Dagger", family = "OneHanded", secondary = true, unlock = {level = 2}, marks = 500},
	{id = "Longsword", name = "Longsword", family = "TwoHanded", secondary = false, unlock = {level = 3}, marks = 900},
	{id = "Mace", name = "Flanged Mace", family = "OneHanded", secondary = true, unlock = {level = 4}, marks = 900},
	{id = "Cleaver", name = "Cleaver", family = "OneHanded", secondary = true, unlock = {level = 4}, marks = 600},
	{id = "Falchion", name = "Falchion", family = "OneHanded", secondary = true, unlock = {level = 6}, marks = 1000},
	{id = "BattleAxe", name = "Battle Axe", family = "TwoHanded", secondary = false, unlock = {level = 7}, marks = 1300},
	{id = "MorningStar", name = "Morning Star", family = "OneHanded", secondary = false, unlock = {level = 8}, marks = 1200},
	{id = "Halberd", name = "Halberd", family = "Polearm", secondary = false, unlock = {level = 8}, marks = 1600},
	{id = "Messer", name = "Kriegsmesser", family = "OneHanded", secondary = false, unlock = {level = 9}, marks = 1300},
	{id = "Maul", name = "Maul", family = "TwoHanded", secondary = false, unlock = {level = 10}, marks = 1800},
	{id = "Billhook", name = "Billhook", family = "Polearm", secondary = false, unlock = {level = 10}, marks = 1200},
	{id = "Estoc", name = "Estoc", family = "TwoHanded", secondary = false, unlock = {level = 11}, marks = 1500},
	{id = "Rapier", name = "Rapier", family = "OneHanded", secondary = true, unlock = {level = 12}, marks = 1500},
	{id = "Glaive", name = "Glaive", family = "Polearm", secondary = false, unlock = {level = 13}, marks = 1600},
	{id = "Poleaxe", name = "Poleaxe", family = "Polearm", secondary = false, unlock = {level = 14}, marks = 1800},
	{id = "Bardiche", name = "Bardiche", family = "TwoHanded", secondary = false, unlock = {level = 15}, marks = 1800},
	{id = "Zweihander", name = "Zweihander", family = "TwoHanded", secondary = false, unlock = {level = 16}, marks = 2200},
	{id = "Executioner", name = "Executioner's Sword", family = "TwoHanded", secondary = false, unlock = {level = 18}, marks = 2400},
	{id = "WarAxe", name = "War Axe", family = "OneHanded", secondary = true, unlock = {level = 3}, marks = 500},
	{id = "Spear", name = "Spear", family = "Polearm", secondary = false, unlock = {free = true}},
	{id = "Quarterstaff", name = "Quarterstaff", family = "Polearm", secondary = false, unlock = {level = 3}, marks = 400},
	{id = "Bow", name = "Longbow", family = "Ranged", secondary = false, ranged = true, unlock = {free = true}},
	{id = "Crossbow", name = "Crossbow", family = "Ranged", secondary = false, ranged = true, unlock = {level = 3}, marks = 600},
	-- the Mage's (GameConfig.CLASSES.Mage): only a magic class carries one, and a magic class carries one
	-- slots = how many spells it carries (LOADOUT ▸ SPELLS); Tools ▸ <id> ▸ Config says the rest
	{id = "Staff", name = "Arcane Staff", family = "Magic", secondary = false, magic = true, slots = 4, unlock = {free = true}},
	{id = "Tome", name = "Grimoire", family = "Magic", secondary = false, magic = true, slots = 5, unlock = {level = 6}, marks = 1200},
	{id = "Wand", name = "Wand", family = "Magic", secondary = true, magic = true, slots = 0, unlock = {free = true}},
}
