"""Write roblox/ServerScriptService/Build/_SkinUploads.lua (GITIGNORED: it holds
asset ids, which never go in the repo) from the Forge's jsons and the upload
record, for Build ▸ SkinModels to assemble in Studio:

    python scripts/skin_entries.py
    -- Studio (command bar / MCP), in batches:
    local B = game.ServerScriptService.Build
    require(B.SkinModels).build(require(B._SkinUploads), 1, 40)

Delete the file again afterwards (Rojo removes the module from the place).
"""
import glob, json, os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SKINS = os.path.join(ROOT, "blender", "out", "skins")
OUT = os.path.join(ROOT, "roblox", "ServerScriptService", "Build", "_SkinUploads.lua")


def lua_str(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main():
    ups = json.load(open(os.path.join(SKINS, "uploads.json")))
    rows, missing = [], 0
    for jf in sorted(glob.glob(os.path.join(SKINS, "*.json"))):
        if jf.endswith("uploads.json"):
            continue
        m = json.load(open(jf, encoding="utf-8"))
        regs = []
        ok = True
        for region, r in m["regions"].items():
            u = ups.get(r["file"])
            if not u:
                ok = False
                break
            c = r["center"]
            regs.append("%s = {id = %d, center = {%.4f, %.4f, %.4f}}" % (region, u["id"], c[0], c[1], c[2]))
        if not ok:
            missing += 1
            continue
        glow = m.get("glow")
        rows.append("\t{weapon = %s, skin = %s, %sregions = {%s}}," % (
            lua_str(m["weapon"]), lua_str(m["skin"]), ("glow = {%d, %d, %d}, " % tuple(glow)) if glow else "", ", ".join(regs)))
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write("-- GENERATED by scripts/skin_entries.py; gitignored (asset ids). Delete after building.\nreturn {\n")
        f.write("\n".join(rows))
        f.write("\n}\n")
    print(f"{len(rows)} skins written, {missing} still missing uploads")


if __name__ == "__main__":
    main()
